feat: Практика 8-01, добавил класс Message и отрефакторил
vartashevich/qa-automation-java pull request #12
Opened 2022-05-04 07:52 UTC by vartashevich

feat: Практика 8-01, добавил класс Message и отрефакторил

2022-05-05 08:41 UTC, yuri-kudryavtsev requested changes

2022-05-05 08:41 UTC, yuri-kudryavtsev commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +        printAdditionalMessages(sortedMessages);
Думаю, учитывая, что теперь печатаем не просто дополнительные сообщения, а все сообщения, можно переименовать в "printMessages"

2022-05-05 08:41 UTC, yuri-kudryavtsev commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +            Message[] sortedMessages = new Message[processedMessages.length];
Для чего выделять память под массив, когда order = ASC или default? 
Можно ведь просто вернуть тот же входной массив неизменным?

2022-05-05 08:41 UTC, yuri-kudryavtsev commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +                        for (int i = 0, j = 0; i <= allMessages.length - 1; i++, j = j + 2) {
Для чего нужна переменная j? 

Можно просто пробежаться по allMessages, используя i : [0...allMessages.length), тогда processedMessages[i*2] и processedMessages[i * 2 +1] должны будут равняться allMessages[i].

2022-05-05 08:41 UTC, yuri-kudryavtsev commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +                        System.arraycopy(allMessages, 0, processedMessages, 0, allMessages.length - 1 + 1);
Для чего выделять копию массива, когда можно вернуть исходный массив?

2022-05-05 08:41 UTC, yuri-kudryavtsev commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +                System.arraycopy(allMessages, 0, processedMessages, 0, allMessages.length - 1 + 1);
И тут не нужна копия.

2022-05-05 08:41 UTC, yuri-kudryavtsev commented on src/main/java/com/tcs/edu/processor/MessageService.java
>       * @param message  Основное троковое сообщение, которое нужно обработать
**С**троковое

2022-05-05 08:41 UTC, yuri-kudryavtsev commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +    private static void printMessage(Message message) {
Инкапсулируй метод  private static void printMessage(Message message) внутрь класса Message.
Там у тебя будет доступ к this.getBody() и this.getSeverity().

Метод перестанет быть статичным.

2022-05-05 08:41 UTC, yuri-kudryavtsev commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +                printMessage(current);
после того, как ты перенесешь метод printMessage внутрь класса Message, вызов поменяется в следующую сторону:
`for (Message current : additionalMessages) {
                current.printMessage();`

2022-05-05 10:32 UTC, vartashevich commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +        printAdditionalMessages(sortedMessages);
исправил

2022-05-05 10:32 UTC, vartashevich commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +            Message[] sortedMessages = new Message[processedMessages.length];
поправил

2022-05-05 10:32 UTC, vartashevich commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +                        for (int i = 0, j = 0; i <= allMessages.length - 1; i++, j = j + 2) {
+

2022-05-05 10:32 UTC, vartashevich commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +                        System.arraycopy(allMessages, 0, processedMessages, 0, allMessages.length - 1 + 1);
+

2022-05-05 10:32 UTC, vartashevich commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +                System.arraycopy(allMessages, 0, processedMessages, 0, allMessages.length - 1 + 1);
+

2022-05-05 10:33 UTC, vartashevich commented on src/main/java/com/tcs/edu/processor/MessageService.java
>       * @param message  Основное троковое сообщение, которое нужно обработать
+

2022-05-05 10:33 UTC, vartashevich commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +    private static void printMessage(Message message) {
в следующем задании буду методы рефакторить, тут оставил бы как есть

2022-05-05 10:34 UTC, vartashevich commented on src/main/java/com/tcs/edu/processor/MessageService.java
> +                printMessage(current);
аналогично, в следующем задании

2022-05-06 12:39 UTC, yuri-kudryavtsev approved these changes

2022-05-06 12:39 UTC, merged